### ISSUE TITLE
Add "view" link for  services, items, and bundles.

### ISSUE THREAD

**Issue by oliviacrosby** [SquaredLabs/nucore-uconn#20] opened 2018-05-24 17:22 UTC
Updated mock up with "view" link to the right of the "purchase" link for Example Facility view of instruments, services, items, and bundles.

**Comment by ColinMcNeil** [comment] 2018-06-25 16:37
Is this a duplicate of #8 ?

**Closed** 2018-09-14 13:55 UTC
